# Generated by Django 2.0.1 on 2019-04-18 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userprofile_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='level',
            field=models.IntegerField(default=0, verbose_name='权限等级'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='密码'),
        ),
    ]
