# Generated by Django 2.0.1 on 2019-05-27 03:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gcckcache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('diaodanHao', models.CharField(max_length=100)),
                ('ToItemName', models.CharField(max_length=100)),
                ('ToItemSlot', models.CharField(max_length=50)),
                ('itemName', models.CharField(max_length=100)),
                ('itemId', models.CharField(max_length=50)),
                ('itemNet', models.CharField(max_length=100)),
                ('op_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
