# Generated by Django 2.0.1 on 2019-05-27 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ywktCache', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='gcckcache',
            new_name='ywktcache',
        ),
    ]
