# Generated by Django 2.0.1 on 2019-05-13 03:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_user_name', models.CharField(max_length=50)),
                ('op_type', models.CharField(max_length=50)),
                ('op_description', models.CharField(max_length=1000)),
                ('op_item', models.CharField(max_length=50)),
                ('op_status', models.CharField(max_length=50)),
                ('op_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
