# Generated by Django 2.0.1 on 2019-05-14 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cache', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cache',
            name='op_description',
        ),
        migrations.AddField(
            model_name='cache',
            name='op_item_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
