# Generated by Django 2.0.1 on 2019-05-27 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cache', '0002_auto_20190514_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='cache',
            name='op_reason',
            field=models.CharField(default='', max_length=100),
        ),
    ]
