# Generated by Django 2.0.1 on 2019-04-24 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=10)),
                ('op_date', models.DateField(auto_now=True)),
                ('op_type', models.CharField(max_length=100)),
                ('op_res', models.BooleanField()),
                ('op_item', models.CharField(max_length=100)),
            ],
        ),
    ]
