# Generated by Django 2.0.1 on 2019-04-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='op_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
