# Generated by Django 2.0.1 on 2019-05-14 01:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20190430_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='op_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
