# Generated by Django 2.0.1 on 2019-05-15 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guangMoKuai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guangmokuai',
            name='change',
            field=models.IntegerField(default=0),
        ),
    ]
