# Generated by Django 2.0.1 on 2019-05-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guangMoKuai', '0002_guangmokuai_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='guangmokuai',
            name='status',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
