# Generated by Django 2.0.1 on 2019-04-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chengzaiwang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fengongsi', models.CharField(blank=True, max_length=100, null=True, verbose_name='分公司')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='配件名称')),
                ('xinghao', models.CharField(blank=True, max_length=100, null=True, verbose_name='规格型号')),
                ('leixing', models.CharField(blank=True, max_length=100, null=True, verbose_name='类型')),
                ('sn', models.CharField(blank=True, max_length=100, null=True, verbose_name='序列号')),
                ('rukushijian', models.CharField(blank=True, max_length=100, null=True, verbose_name='入库时间')),
                ('rukudidian', models.CharField(blank=True, max_length=100, null=True, verbose_name='入库地点')),
                ('num', models.CharField(blank=True, max_length=100, null=True, verbose_name='数量')),
                ('huoweihao', models.CharField(blank=True, max_length=100, null=True, verbose_name='货位号')),
                ('dingdanhao', models.CharField(blank=True, max_length=100, null=True, verbose_name='订单号')),
                ('diaochushijian', models.CharField(blank=True, max_length=100, null=True, verbose_name='调出时间')),
                ('diaowangdi', models.CharField(blank=True, max_length=100, null=True, verbose_name='调往地')),
                ('suoshuwangluo', models.CharField(blank=True, max_length=100, null=True, verbose_name='所属网络')),
                ('beizhu', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('zichanbiaoqian', models.CharField(blank=True, max_length=100, null=True, verbose_name='资产标签')),
                ('status', models.CharField(default='未出库', max_length=100, verbose_name='状态')),
            ],
        ),
    ]
