# Generated by Django 2.0.1 on 2019-04-30 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chengzaiwang', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chengzaiwang',
            name='status',
        ),
    ]
