# Generated by Django 2.0.1 on 2019-05-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chengzaiwang', '0003_chengzaiwang_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chengzaiwang',
            name='rukushijian',
            field=models.DateField(auto_now=True, verbose_name='入库时间'),
        ),
    ]
