# Generated by Django 2.0.1 on 2019-05-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chengzaiwang', '0004_auto_20190508_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chengzaiwang',
            name='rukushijian',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='入库时间'),
        ),
    ]
