# Generated by Django 2.0.1 on 2019-05-08 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='yi69',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changjia', models.CharField(max_length=50)),
                ('mingcheng', models.CharField(max_length=100)),
                ('xinghao', models.CharField(max_length=100)),
                ('sn', models.CharField(blank=True, max_length=100, null=True)),
                ('num', models.CharField(blank=True, max_length=50, null=True)),
                ('place', models.CharField(blank=True, max_length=50, null=True)),
                ('beizhu', models.CharField(blank=True, max_length=50, null=True)),
                ('gongcheng', models.CharField(blank=True, max_length=50, null=True)),
                ('zichanbiaoqian', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
