# Generated by Django 2.0.1 on 2019-05-08 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yi69', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yi69',
            name='beizhu',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='yi69',
            name='gongcheng',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
