# Generated by Django 2.0.1 on 2019-05-14 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yi69', '0002_auto_20190508_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='yi69',
            name='status',
            field=models.CharField(default='未出库', max_length=50),
        ),
    ]
